### Create task

POST http://localhost:3030/api/tasks
Content-Type: application/json

{
    "title": "Avenged Sevenfold",
    "description": "I love band"
}

### List tasks


GET http://localhost:3030/api/tasks
Content-Type: application/json

### Get tasks

GET http://localhost:3030/api/tasks/1
Content-Type: application/json

### Update task

PUT http://localhost:3030/api/tasks/1
Content-Type: application/json

{
    "title": "Avenged Sevenfold",
    "description": "I love band"
}

### Delete task

DELETE  http://localhost:3030/api/tasks/1
Content-Type: application/json

{
    "title": "Avenged Sevenfold",
    "description": "I love band"
}